In [1]:
# to import files from googledrive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [2]:
import pandas as pd
import os

HTN i.e. icd9=4019 dataset
Diabetes i.e. icd9=25000 dataset

In [3]:
#df_htn = pd.read_csv('gdrive/My Drive/sample_size/data/20000_htn_all_data_v4_090822.csv') 

df_diab = pd.read_csv('gdrive/My Drive/sample_size/diabetes/diabetes_text.csv')

In [4]:
#df_htn.head()

df_diab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs
0,57004,25000,F,2077-06-18 00:00:00,WHITE,Admission Date: [**2152-10-11**] ...,34
1,82773,25000,M,2071-06-12 00:00:00,WHITE,[**2136-10-23**] 5:05 PM\n CT CHEST W/CONTRAST...,7
2,75261,25000,F,2105-11-07 00:00:00,BLACK/AFRICAN AMERICAN,Admission Date: [**2156-8-4**] D...,5
3,91136,25000,M,2099-12-18 00:00:00,WHITE,[**2159-8-20**] 12:34 PM\n T-SPINE IN O.R.; SP...,22
4,88206,25000,F,2042-02-01 00:00:00,WHITE,[**2103-9-19**] 1:06 PM\n CAROT/CEREB [**Hospi...,46

In [5]:
#df_htn['text'][55]

df_diab['text'][55]

'[**2191-12-15**] 1:52 PM\n BOTH KNEES STANDING AP ONLY; KNEE (2 VIEWS) BILAT               Clip # [**Clip Number (Radiology) 104800**]\n Reason: Pt w/bilat knee pain\n ______________________________________________________________________________\n [**Hospital 2**] MEDICAL CONDITION:\n  79 year old woman w/bilat knee pain\n REASON FOR THIS EXAMINATION:\n  Pt w/bilat knee pain\n ______________________________________________________________________________\n                                 FINAL REPORT\n HISTORY:  Bilateral knee pain.\n\n FINDINGS:  There is tricompartmental hypertrophic spurring bilaterally with\n substantial narrowing of the medial compartments.  No evidence of joint\n effusion.  Superior patellar spurring is seen bilaterally.\n\n IMPRESSION:  Degenerative changes primarily involving the medial compartments.\n\n\n'

In [6]:
#df_htn.describe()

df_diab.describe()

         subject_id  icd9_code   no_of_docs
count   5637.000000     5637.0  5637.000000
mean   32883.095086    25000.0    36.632251
std    27847.500129        0.0    10.399956
min       20.000000    25000.0     5.000000
25%    12071.000000    25000.0    30.000000
50%    21642.000000    25000.0    39.000000
75%    55579.000000    25000.0    45.000000
max    99999.000000    25000.0    50.000000

Randomly select x rows

In [20]:
#df_6000_htn = df_htn.sample(n=6000, random_state=1)

df_5000_diab = df_diab.sample(n=5000, random_state=1)

In [21]:
#df_6000_htn.head()

df_5000_diab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs
2939,9027,25000,M,2073-02-22 00:00:00,UNKNOWN/NOT SPECIFIED,RN PROGRESS NOTE\nneuro: intact w/o issues\nCV...,40
4983,31898,25000,F,2064-02-09 00:00:00,WHITE,[**2150-7-16**] 11:45 AM\n FEMUR (AP & LAT) LE...,48
941,77014,25000,M,2057-11-13 00:00:00,WHITE,[**2128-12-10**] 11:37 PM\n CHEST (PA & LAT) ...,25
4829,13930,25000,M,2097-04-19 00:00:00,HISPANIC OR LATINO,Nursing Note-Discharged Home A shift\nPlease s...,48
940,26713,25000,M,2061-09-28 00:00:00,WHITE,Baseline artifact\nSinus rhythm\nSince previou...,25

In [22]:
#df_6000_htn.describe()

df_5000_diab.describe()

         subject_id  icd9_code   no_of_docs
count   5000.000000     5000.0  5000.000000
mean   33133.615600    25000.0    36.610200
std    27917.693045        0.0    10.386348
min       20.000000    25000.0     5.000000
25%    12138.250000    25000.0    30.000000
50%    21808.000000    25000.0    39.000000
75%    56186.000000    25000.0    45.000000
max    99999.000000    25000.0    50.000000

In [23]:
#df_6000_htn['label'] = 1

df_5000_diab['label'] = 1

In [24]:
#df_6000_htn.head()

df_5000_diab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs,label
2939,9027,25000,M,2073-02-22 00:00:00,UNKNOWN/NOT SPECIFIED,RN PROGRESS NOTE\nneuro: intact w/o issues\nCV...,40,1
4983,31898,25000,F,2064-02-09 00:00:00,WHITE,[**2150-7-16**] 11:45 AM\n FEMUR (AP & LAT) LE...,48,1
941,77014,25000,M,2057-11-13 00:00:00,WHITE,[**2128-12-10**] 11:37 PM\n CHEST (PA & LAT) ...,25,1
4829,13930,25000,M,2097-04-19 00:00:00,HISPANIC OR LATINO,Nursing Note-Discharged Home A shift\nPlease s...,48,1
940,26713,25000,M,2061-09-28 00:00:00,WHITE,Baseline artifact\nSinus rhythm\nSince previou...,25,1

In [25]:
#df_6000_htn.describe()

df_5000_diab.describe()

         subject_id  icd9_code   no_of_docs   label
count   5000.000000     5000.0  5000.000000  5000.0
mean   33133.615600    25000.0    36.610200     1.0
std    27917.693045        0.0    10.386348     0.0
min       20.000000    25000.0     5.000000     1.0
25%    12138.250000    25000.0    30.000000     1.0
50%    21808.000000    25000.0    39.000000     1.0
75%    56186.000000    25000.0    45.000000     1.0
max    99999.000000    25000.0    50.000000     1.0

Non-HTN i.e. icd9 != 4019 dataset

Non-diabetes i.e. icd9 != 25000 dataset

In [13]:
#df_nonhtn = pd.read_csv('gdrive/My Drive/sample_size/data/20000_nonhtn_all_data_v4_090822.csv') 

df_nondiab = pd.read_csv('gdrive/My Drive/sample_size/diabetes/non_diabetes_text.csv')

In [14]:
#df_nonhtn.head()
df_nondiab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs
0,19252,4784,F,2119-06-01 00:00:00,HISPANIC OR LATINO,Sinus bradycardia\nLong QTc interval - clinica...,20
1,19252,496,F,2119-06-01 00:00:00,HISPANIC OR LATINO,Sinus bradycardia\nLong QTc interval - clinica...,20
2,19252,42731,F,2119-06-01 00:00:00,HISPANIC OR LATINO,Sinus bradycardia\nLong QTc interval - clinica...,20
3,19252,4019,F,2119-06-01 00:00:00,HISPANIC OR LATINO,Sinus bradycardia\nLong QTc interval - clinica...,20
4,5923,7454,M,2135-02-15 00:00:00,WHITE,"Atrial fibrillation, rate 60-100. Flat T waves...",24

In [15]:
df_nondiab['icd9_code'].value_counts()

4019     300
41401    198
V053     170
V290     121
V3000    116
        ...
44100      1
5559       1
9779       1
5722       1
3180       1
Name: icd9_code, Length: 1068, dtype: int64

In [16]:
#check none of the htn-like diagnoses are included
#df_nonhtn[df_nonhtn['icd9_code'].isin([9726, 5723, 4160,4010,99791])]

#check non of the diab-like diagnosis are included
df_nondiab[df_nondiab['icd9_code'].isin([25060,
25040,
25002,
25080,
25050,
25061,
25013,
25041,
25001])]

Empty DataFrame
Columns: [subject_id, icd9_code, gender, dob, ethnicity, text, no_of_docs]
Index: []

In [17]:
#df_nonhtn.describe()

df_nondiab.describe()

         subject_id   no_of_docs
count   5000.000000  5000.000000
mean   36272.875800    33.206600
std    29118.371136    12.243378
min       27.000000     3.000000
25%    12608.000000    24.000000
50%    24506.000000    35.000000
75%    62334.000000    44.000000
max    99999.000000    50.000000

Randomly select x rows

In [18]:
#df_6000_nonhtn = df_nonhtn.sample(n=6000, random_state=1)

df_5000_nondiab = df_nondiab.sample(n=5000, random_state=1)

In [19]:
#df_6000_nonhtn.head()

df_5000_nondiab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs
2764,79002,2768,F,2097-03-13 00:00:00,WHITE,Admission Date: [**2165-5-7**] D...,31
4767,9568,2720,M,2146-10-25 00:00:00,UNKNOWN/NOT SPECIFIED,[**4-21**] B; SHIFT SUMMARY;\n\nNEURO; ARRIVED...,48
3814,11649,V290,F,2197-10-19 00:00:00,PATIENT DECLINED TO ANSWER,Neonatology Attending\n\nFT infant referred to...,10
3499,24282,V1009,F,2048-10-25 00:00:00,UNKNOWN/NOT SPECIFIED,Sinus tachycardia. Since the previous tracing ...,45
2735,79002,2763,F,2097-03-13 00:00:00,WHITE,Admission Date: [**2165-5-7**] D...,31

In [26]:
#df_6000_nonhtn.describe()

df_5000_nondiab.describe()

         subject_id   no_of_docs
count   5000.000000  5000.000000
mean   36272.875800    33.206600
std    29118.371136    12.243378
min       27.000000     3.000000
25%    12608.000000    24.000000
50%    24506.000000    35.000000
75%    62334.000000    44.000000
max    99999.000000    50.000000

In [27]:
#df_6000_nonhtn['label'] = 0

df_5000_nondiab['label'] = 0

In [28]:
#df_6000_nonhtn.head()

df_5000_nondiab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs,label
2764,79002,2768,F,2097-03-13 00:00:00,WHITE,Admission Date: [**2165-5-7**] D...,31,0
4767,9568,2720,M,2146-10-25 00:00:00,UNKNOWN/NOT SPECIFIED,[**4-21**] B; SHIFT SUMMARY;\n\nNEURO; ARRIVED...,48,0
3814,11649,V290,F,2197-10-19 00:00:00,PATIENT DECLINED TO ANSWER,Neonatology Attending\n\nFT infant referred to...,10,0
3499,24282,V1009,F,2048-10-25 00:00:00,UNKNOWN/NOT SPECIFIED,Sinus tachycardia. Since the previous tracing ...,45,0
2735,79002,2763,F,2097-03-13 00:00:00,WHITE,Admission Date: [**2165-5-7**] D...,31,0

In [29]:
#df_6000_nonhtn.describe()

df_5000_nondiab.describe()

         subject_id   no_of_docs   label
count   5000.000000  5000.000000  5000.0
mean   36272.875800    33.206600     0.0
std    29118.371136    12.243378     0.0
min       27.000000     3.000000     0.0
25%    12608.000000    24.000000     0.0
50%    24506.000000    35.000000     0.0
75%    62334.000000    44.000000     0.0
max    99999.000000    50.000000     0.0

Merge HTN with nonHTN

Merge Diabetes with Non-diabetes

In [30]:
#data_for_classifier_12k = df_6000_htn.append(df_6000_nonhtn, ignore_index=True)

data_for_classifier_10k = df_5000_diab.append(df_5000_nondiab, ignore_index=True)

<ipython-input-30-f5566b591cf3>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_for_classifier_10k = df_5000_diab.append(df_5000_nondiab, ignore_index=True)

In [31]:
#data_for_classifier_12k.head()

data_for_classifier_10k.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs,label
0,9027,25000,M,2073-02-22 00:00:00,UNKNOWN/NOT SPECIFIED,RN PROGRESS NOTE\nneuro: intact w/o issues\nCV...,40,1
1,31898,25000,F,2064-02-09 00:00:00,WHITE,[**2150-7-16**] 11:45 AM\n FEMUR (AP & LAT) LE...,48,1
2,77014,25000,M,2057-11-13 00:00:00,WHITE,[**2128-12-10**] 11:37 PM\n CHEST (PA & LAT) ...,25,1
3,13930,25000,M,2097-04-19 00:00:00,HISPANIC OR LATINO,Nursing Note-Discharged Home A shift\nPlease s...,48,1
4,26713,25000,M,2061-09-28 00:00:00,WHITE,Baseline artifact\nSinus rhythm\nSince previou...,25,1

In [32]:
#data_for_classifier_12k.describe()

data_for_classifier_10k.describe()

         subject_id    no_of_docs         label
count  10000.000000  10000.000000  10000.000000
mean   34703.245700     34.908400      0.500000
std    28566.084337     11.479189      0.500025
min       20.000000      3.000000      0.000000
25%    12254.000000     27.000000      0.000000
50%    23109.500000     36.000000      0.500000
75%    58705.000000     45.000000      1.000000
max    99999.000000     50.000000      1.000000

In [33]:
#data_for_classifier_12k['label'].value_counts()

data_for_classifier_10k['label'].value_counts()

1    5000
0    5000
Name: label, dtype: int64

Shuffle the rows

In [34]:
from sklearn.utils import shuffle
#data_for_classifier = shuffle(data_for_classifier_12k)

data_for_classifier_diab = shuffle(data_for_classifier_10k)

In [35]:
#data_for_classifier_12k.head()

data_for_classifier_diab.head()

,subject_id,icd9_code,gender,dob,ethnicity,text,no_of_docs,label
7389,10935,V290,M,2184-03-22 00:00:00,WHITE,Nursing Progress Note\n\n\n#1 Continues on AMP...,26,0
2602,56746,25000,M,2076-12-22 00:00:00,WHITE,[**2143-2-26**] 8:47 AM\n CTA ABD & PELVIS ...,49,1
7986,93337,30000,M,2083-10-22 00:00:00,WHITE,Sinus rhythm. Normal tracing. Compared to the ...,35,0
2516,63192,25000,M,2130-01-20 00:00:00,WHITE,[**2193-9-9**] 11:45 AM\n CHEST PORT. LINE PLA...,40,1
9324,12451,4738,F,2091-07-09 00:00:00,WHITE,Nursing Progress/Transfer note 0700-1300\nPt a...,28,0

In [36]:
#data_for_classifier_12k.to_csv('gdrive/My Drive/sample_size/data/12k_data_for_classifier.csv')

data_for_classifier_diab.to_csv('gdrive/My Drive/sample_size/diabetes/10k_data_for_classifier_diab.csv')